### ISSUE TITLE
Any help for open data module configuration

### ISSUE THREAD

**Issue by phavira** [nordic-institute/X-Road-Metrics#110]
Hi ! 

i'm try to access api/statistics, but i got error.  undefinded Table metrics_statistics. how can i genrate table metrics_statistics. thanks 

![Capture123](https://github.com/nordic-institute/X-Road-Metrics/assets/42505779/8fafb056-821c-4460-9bee-5d2e4c80b52a)

**Comment by phavira168** [comment]
Hello @raits, 

i'm really follow your document. but still missing that table. can you share process to migrate that table ?

**Comment by raits** [comment]
In case the database setup has been done, the statistics table should be generated automatically by the anonymizer modules statistics command  when it is ran: https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs/anonymizer_module.md#metrics-statistics

The `Central Monitoring Client` in that diagram referst to the Security Server that has the relevant subsystem registered to it. Information on configuring the monitoring client for your instance can be found here: https://docs.x-road.global/Manuals/ug-cs_x-road_6_central_server_user_guide.html#14-monitoring

**Comment by phavira** [comment]
the Central Monitoring Client. i upload file monitoring-params.xml to  Central Configuration already but. the result return UnknownMember.

**Comment by phavira** [comment]
I have to run success on anonymize command. but still not generate table metrics_statistics. what should i do now ? 

```
[
    {
        "level": "INFO",
        "timestamp": 1715049670,
        "local_timestamp": "2024-05-07 02:41:10 +0000",
        "module": "anonymizer",
        "activity": "anonymization_session_started",
        "msg": "Started anonymization session",
        "version": "1.2.0"
    },
    {
        "level": "INFO",
        "timestamp": 1715049670,
        "local_timestamp": "2024-05-07 02:41:10 +0000",
        "module": "anonymizer",
        "activity": "anonymization_process_started",
        "msg": "Started anonymizing logs.",
        "version": "1.2.0"
    },
    {
        "level": "INFO",
        "timestamp": 1715049670,
        "local_timestamp": "2024-05-07 02:41:10 +0000",
        "module": "anonymizer",
        "activity": "anonymization_session_finished",
        "msg": "Anonymization finished in 0:00:00.117990 seconds. Processed 58 entries from MongoDB.",
        "version": "1.2.0"
    }
]
```

**Comment by raits** [comment]
Hello @phavira,

The statistics command needs to be ran separately as mentioned here: https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs/anonymizer_module.md#metrics-statistics

Have you tried running it and seeing if additional information becomes available?

**Comment by phavira168** [comment]
I got it. Thank you

**Comment by phavira** [comment]
I got it. thank you.
