### ISSUE TITLE
[Errno 111] Connection refused on road-metrics-colloector module 

### ISSUE THREAD

**Issue by zemdem** [nordic-institute/X-Road-Metrics#147]
Hello community, 
I am encountering a problem on xroad-metric-collector that I cannot resolve. The **xroad-metrics-collector collect** command returns following error: 
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='<servername>', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection .HTTPConnection object at 0x721f5070c6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Do you have an idea ? 

Thank you in advance and best regards

**Comment by raits** [comment]
Based on the error containing the placeholder `<servername>`, it seems like you have not configured the component.

Please refer to the documentation on how to set things up: https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs/collector_module.md

**Comment by zemdem** [comment]
I have followed the documentation. Finally I have fixed the issue by using 8080port number instead of 80 in the connexion code file /usr/local/lib/python3.10/dist-packages/urllib3/connection.py
`port_by_scheme = {"http": 8080, "https": 443}`
Now I have my two DBs Mongo & Postgres populated. But I have another problem :
I can't see metrics regarding SI service calls. I only see the service getSecurityServerOperationalData in the list (please see in attached the extract of the data). 

When I run the xroad-metrics-networking data preparation script no data is generated and I got this  : 
`{"module":"networking_module", "local_timestamp":"2024-11-13 21:10:54", "timestamp":1731532255, "duration":"00:00:00", "level":"INFO", "activity":"data preparation ended", "msg":"0 rows were written for visualizer"}`

When I run the shiny APP, it's failed to load data with following error 
`Warning: Error in UseMethod: no applicable method for 'filter' applied to an object of class "NULL"
  225: %>%
  224: <reactive:dat2> [/usr/share/xroad-metrics/networking/shiny/app.R#121]
  222: .func
  219: contextFunc
  218: env$runWith
  211: ctx$run
  210: self$.updateValue
  208: dat2
  190: <reactive:net> [/usr/share/xroad-metrics/networking/shiny/app.R#154]
  188: .func
  185: contextFunc
  184: env$runWith
  177: ctx$run
  176: self$.updateValue
  174: net
  167: renderPlot [/usr/share/xroad-metrics/networking/shiny/app.R#184]
  165: func
  125: drawPlot
  111: <reactive:plotObj>
   95: drawReactive
   82: origRenderFunc
   81: output$net1
    1: runApp
Warning: Error in UseMethod: no applicable method for 'filter' applied to an object of class "NULL"
  176: <Anonymous>


Execution halted
`
[logs.csv](https://github.com/user-attachments/files/17739409/logs.csv)

Thank you in advance for your help.

**Comment by raits** [comment]
The default settings have a delay of since when Metrics are collected, these can be configured in the settings file for:

- collector
- networking
- opendata

Additionally it would be worth checking that the opmon addon is installed on the Security Servers so that data is actually collected.

**Comment by zemdem** [comment]
In security servers opmon addons have been installed. Here the list of services running:

```
$ sudo systemctl list-units "xroad-*"
  UNIT                           LOAD   ACTIVE SUB     DESCRIPTION               
  xroad-addon-messagelog.service loaded active running X-Road Messagelog Archiver
  xroad-base.service             loaded active exited  X-Road initialization
  xroad-confclient.service       loaded active running X-Road confclient
  xroad-monitor.service          loaded active running X-Road Monitor
  xroad-opmonitor.service        loaded active running X-Road opmonitor daemon
  xroad-proxy-ui-api.service     loaded active running X-Road Proxy UI REST API
  xroad-proxy.service            loaded active running X-Road Proxy
  xroad-signer.service           loaded active running X-Road signer
```
 I executed the commands manually and observed the batch executions. This is not enough? Could you tell me the correct conf in the different modules please?

**Comment by zemdem** [comment]
Hi,

Thank you very much Raits. Seems better after modifying conf in specified modules and setting delays to 0. Now datas on the DB are published in opendata & shiny App. However only metaservices stats (getSecurityServerOperationalData) are published. All the rows have "clientSubsystemCode" as MONITORING and "serviceCode" as getSecurityServerOperationalData. 

What may explain that real services call are not collected ?

**Comment by raits** [comment]
Hey,

I am glad you got it running. As for only the monitoring info being collected, the simplest answer would be that likely that Security Servers that are collecting the operational monitoring data have not seen any other activity. Could you send a test query through the Security Server that you listed the services for and see if those reach the Metrics after running the collector, corrector, anonymizer and opendata / networking processes?

**Comment by zemdem** [comment]
I've tried out running a request to reach a service in the same security server (provider & consumer client in the same security server where the MONITORING service have been declared). 
After running collect/corrector/anonimyzer/networking services, I have the same result. Only monitoring metrics are available on database. 
I don't know if it's something related, but in my global conf I have now monitoring conf as shown in attached image : 
<img width="1168" alt="global conf" src="https://github.com/user-attachments/assets/a9367347-57f2-40a3-a2f6-00671907a21c">

**Comment by raits** [comment]
It seems like you probably have not configured the monitoring client for your X-Road instance. Please check the documentation here on how to do so: https://docs.x-road.global/EnvironmentalMonitoring/Monitoring-architecture.html#25-central-server-admin-user-interface

**Comment by zemdem** [comment]
Greatt! It works after uploading monitoring conf to central server. 
Thank you very much Raits. 
Best Regards

**Comment by raits** [comment]
Thank you for the feedback, glad you got it working!
