### ISSUE TITLE
As a Metric user I want logs to report correct application version

### ISSUE THREAD

**Issue by VitaliStupin** [nordic-institute/X-Road-Metrics#36]
Currently application logs report that application version is 1.0.0, but the software was updated to 1.1.0

Software version:
1.1.0

Log example:
```
{"level": "INFO", "timestamp": 1678447142, "local_timestamp": "2023-03-10 13:19:02 +0200", "module": "collector", "activity": "collector_end", "msg": "Total collected: 1, Total error: 1, Total time: 00:00:00", "version": "1.0.0"}
```

Source example:
https://github.com/nordic-institute/X-Road-Metrics/blob/develop/collector_module/opmon_collector/__init__.py#L23
But the problem is with other modules as well.

Solution:
Bump versions in `__init__.py` files.

**Comment by raits** [comment]
This was fixed with v1.1.1.
