### ISSUE TITLE
As a Metric user I want opendata DB networking deb package to install correct dependencies

### ISSUE THREAD

**Issue by VitaliStupin** [nordic-institute/X-Road-Metrics#38]
Currently xroad-metrics-networking package does not include required dependencies.

As it was mentioned in https://github.com/nordic-institute/X-Road-Metrics/pull/15 pull request package needs to depend on "r-cran-rodbc" and "odbc-postgresql", and the following dependencies should not be required anymore: "r-cran-rpostgresql" and "r-cran-dbi"

**Comment by wisecrow** [comment]
@VitaliStupin Thanks. Fixing it

**Comment by raits** [comment]
This was fixed with v1.1.1.
