### ISSUE TITLE
As a Metric user I want networking ssl_mode configuration parameter to work

### ISSUE THREAD

**Issue by VitaliStupin** [nordic-institute/X-Road-Metrics#41]
Currently ssl_mode configuration parameter is ignored by networking application:
https://github.com/nordic-institute/X-Road-Metrics/blob/develop/networking_module/prepare_data.R#L63-L83

It seems that odbc-postgresql ignores PGSSLMODE env variable, and it is required to put sslmode parameter into connection string.

For example the following code would fix the problem:
```
#if ("ssl_mode" %in% names(settings$postgres)) {
#    Sys.setenv(PGSSLMODE = settings$postgres$ssl_mode)
#}
if ("ssl_root_cert" %in% names(settings$postgres)) {
    Sys.setenv(PGSSLROOTCERT = settings$postgres$ssl_root_cert)
}

tryCatch(
  con <- odbcDriverConnect(
    connection = paste0(
      "Driver={PostgreSQL UNICODE}",
      ";Server=", settings$postgres$host,
      ";Port=", settings$postgres$port,
      ";Database=opendata_", settings$postgres$suffix,
      ";Uid=", settings$postgres$user,
      ";Pwd=", settings$postgres$password,
      ";UseDeclareFetch=1",
      ";Fetch=", fetchsize,
      ";sslmode=", settings$postgres$ssl_mode,
      ";"
    )
  ),
```

**Comment by raits** [comment]
Hello,

Thank you for the report. We will look into it and release a bugfix at the beginning of May at the latest.

**Comment by raits** [comment]
This issue was fixed.
