### ISSUE TITLE
Opendata Operational monitoring Delay!

### ISSUE THREAD

**Issue by N3tw0rk3r** [nordic-institute/X-Road-Metrics#6]
X-Road monitoring data is collected from Estonian X-Road members security servers available by X-Road Center (Republic of Estonia Information System Authority, Riigi Infosüsteemi Amet, RIA) and published as opendata with a delay of 10 days from actual transaction execution time.

Is there any way to change this behavior to configure opendata as a real-time operational monitoring solution ? or Is there any other operational monitoring product that is real time monitoring instead of 10 days delay?

**Comment by petkivim** [comment]
Duplicate issue - the topic is discussed here:

https://github.com/nordic-institute/X-Road/issues/1327
