### ISSUE TITLE
X-Road metrics installation startup

### ISSUE THREAD

**Issue by jonathanleder** [nordic-institute/X-Road-Metrics#98]
hi, i am just starting to install x-road metrics and i wanted to know where i have to install the modules.

**Comment by raits** [comment]
Hey @jonathanleder!

Please elaborate on the question. Do you mean the recommended setup? If so, then please refer to this document: https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs/system_architecture.md#recommended-infrastructure-for-production-use

**Comment by jonathanleder** [comment]
hello, no, I want to make a demo on X-Road metrics, I have a cs and two ss that are going to act as provider and consumer, my question is how do I couple the metrics modules to my ecosystem?

**Comment by raits** [comment]
Hey, as noted on the linked infrastructure picture, you need to set up the relevant Metrics components, starting with the [collector_module](https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs/collector_module.md) and [corrector_module](https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs/corrector_module.md). For documentation related to the other components please have a look at the documentation under the [docs](https://github.com/nordic-institute/X-Road-Metrics/blob/develop/docs) folder.

**Comment by raits** [comment]
I will close this issue now since it has been inactive for a while, if you have further questions, please feel free to re-open it or create a new one.
